# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"   # On met une version stable plutôt que 3.13

sphinx:
  configuration: docs/conf.py   # Chemin vers ton conf.py

python:
  install:
    - requirements: requirements.txt  # fichier requirements.txt à la racine du projet
  
