# -- Project information -----------------------------------------------------

project = 'VARS - Video Assistant Referee System'
copyright = '2025, AMLLAL Amine, AKEBLI FatimaEzzahrae, ELHAKIOUI Asmae'
author = 'AMLLAL Amine, AKEBLI FatimaEzzahrae, ELHAKIOUI Asmae'
release = '1.0'
version = '1.0'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.githubpages',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'myst_parser',
]

# MyST parser configuration
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "html_image",
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The master toctree document
master_doc = 'index'

# Napoleon settings for Google and NumPy style docstrings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False

# Language for content autogenerated by Sphinx
language = 'en'

# Source file suffixes
source_suffix = {
    '.rst': None,
    '.md': 'myst_parser',
}

# List of patterns for module index generation
autosummary_generate = True

# Todo extension settings
todo_include_todos = True

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

# Theme options
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Custom CSS and JS files
html_css_files = []
html_js_files = []

# HTML context
html_context = {
    'display_github': True,
    'github_user': 'your-github-username',
    'github_repo': 'AnalyseDesFautes',
    'github_version': 'main',
    'conf_py_path': '/docs/',
}

# Add any custom logos
html_logo = None
html_favicon = None

# Social links
html_title = 'VARS Documentation'
html_short_title = 'VARS'

# Show source link
html_show_sourcelink = True
html_show_sphinx = True
html_show_copyright = True

# Intersphinx mapping
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'torch': ('https://pytorch.org/docs/stable/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
}
